version: "3"
services:
 grafana:
  image: grafana/grafana:5.1.0
  environment:
   - GF_SERVER_ROOT_URL=http://192.168.99.100:3000
   - GF_SECURITY_ADMIN_PASSWORD=123456
   - TZ="America/Bahia"
  ports:
   - 3000:3000
  user: "104"
 mongo:
  image: mongo
  restart: always
  ports:
   - 2701:2701
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: example
 mongo-express:
  image: mongo-express
  restart: always
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: root
   ME_CONFIG_MONGODB_ADMINPASSWORD: example